
#Ares HUD UI Properties
[properties]
	#Type of hotbar layout to use.
	#Allowed Values: DEFAULT, HOTBAR_1X9, HOTBAR_1X9_VERTICAL, HOTBAR_3X3
	hotbarType = "HOTBAR_1X9"

	[properties.Layout_DEFAULT]
		hotbarDefaultProperties = "0.0122448979,0.8036363721,1.0395200253"
		offhandDefaultProperties = "0.2729170024,0.7968130112,0.7514969707"
		centerHudDefaultProperties = "0.3163265288,0.8909090757,0.8123130202"
		xpBarDefaultProperties = "0.4795918465,0.8909090757,0.8767590523"
		statusValueBarDefaultProperties = "0.3140625060,0.9281439781,1.0750739574"
		DefaultMainHandOffsets = "0,0,-1,-1"
		hotbarEnabled = true
		centerHudEnabled = true
		xpBarEnabled = true
		statusValueBarEnabled = false
		offhandEnabled = false
		healthBarEnabled = true
		foodBarEnabled = true
		staminaBarEnabled = true
		armorBarEnabled = true
		#Range: 0 ~ 50
		statusHorizontalPadding = 19
		#Range: 0 ~ 50
		statusBarVerticalSpacing = 1
		#Bounds for Flask UI in Default layout. DuelCraft Only
		flaskDefaultProperties = "0.2734375000,0.8892215490,1.1126120090"
		#Enable Flask UI in Default layout. DuelCraft Only
		flaskEnabledDefault = true

	[properties.Layout_HOTBAR_1X9]
		hotbar1x9Properties = "0.3515625000,0.9341317415,0.7815815210"
		offhand1x9Properties = "0.3031249940,0.9311377406,0.7824444175"
		centerHud1x9Properties = "0.3486394584,0.8562874198,0.6702424288"
		xpBar1x9Properties = "0.4829931855,0.8562874198,0.7109642625"
		statusValueBar1x9Properties = "0.6796875000,0.9520958066,0.7747759819"
		1x9MainHandOffsets = "1,1,0,0"
		hotbarEnabled = true
		centerHudEnabled = true
		xpBarEnabled = true
		statusValueBarEnabled = false
		offhandEnabled = true
		healthBarEnabled = true
		foodBarEnabled = true
		staminaBarEnabled = true
		armorBarEnabled = true
		#Range: 0 ~ 50
		statusHorizontalPadding = 17
		#Range: 0 ~ 50
		statusBarVerticalSpacing = 2
		#Bounds for Flask UI in 1x9 layout. DuelCraft Only
		flask1x9Properties = "0.6578124762,0.8832335472,1.1501494646"
		#Enable Flask UI in 1x9 layout. DuelCraft Only
		flaskEnabled1x9 = true

	[properties.Layout_HOTBAR_1X9_VERTICAL]
		hotbar1x9VerticalProperties = "0.9510204196,0.2129963934,0.7628343105"
		offhand1x9VerticalProperties = "0.9530612230,0.7761732936,0.7132092714"
		centerHud1x9VerticalProperties = "0.2816326618,0.8690909147,0.9388849735"
		xpBar1x9VerticalProperties = "0.4734693766,0.8690909147,1.1269459724"
		statusValueBar1x9VerticalProperties = "0.2938775420,0.9458483458,1.1692184210"
		1x9VerticalMainHandOffsets = "1,1,0,0"
		hotbarEnabled = true
		centerHudEnabled = true
		xpBarEnabled = true
		statusValueBarEnabled = false
		offhandEnabled = true
		healthBarEnabled = true
		foodBarEnabled = true
		staminaBarEnabled = true
		armorBarEnabled = true
		#Range: 0 ~ 50
		statusHorizontalPadding = 18
		#Range: 0 ~ 50
		statusBarVerticalSpacing = 4
		#Bounds for Flask UI in 1x9Vertical layout. DuelCraft Only
		flask1x9VerticalProperties = "0.2671875060,0.8802395463,1.1501494646"
		#Enable Flask UI in 1x9Vertical layout. DuelCraft Only
		flaskEnabled1x9Vertical = true

	[properties.Layout_HOTBAR_3X3]
		hotbar3x3Properties = "0.0937500000,0.6932269931,1.1799999475"
		offhand3x3Properties = "0.1437499970,0.5808380246,1.1749249697"
		centerHud3x3Properties = "0.2624999881,0.8263472915,1.0700000525"
		xpBar3x3Properties = "0.4718750119,0.8173652887,1.4145580530"
		statusValueBar3x3Properties = "0.3203125000,0.9520958066,1.0375369787"
		3x3MainHandOffsets = "1,2,1,1"
		hotbarEnabled = true
		centerHudEnabled = true
		xpBarEnabled = true
		statusValueBarEnabled = true
		offhandEnabled = true
		healthBarEnabled = true
		foodBarEnabled = true
		staminaBarEnabled = true
		armorBarEnabled = true
		#Range: 0 ~ 50
		statusHorizontalPadding = 20
		#Range: 0 ~ 50
		statusBarVerticalSpacing = 4
		#Bounds for Flask UI in 3x3 layout. DuelCraft Only
		flask3x3Properties = "0.2687500119,0.8802395463,1.1876868010"
		#Enable Flask UI in 3x3 layout. DuelCraft Only
		flaskEnabled3x3 = true

	[properties.Global_Offsets]
		defaultOffHandOffsets = "0,0,0,0"
		separateOffHandOffsets = "-2,-3,0,0"
		selectedItemNameOffsets = "2,0,0,0"

	[properties.Global_Buff_Settings]
		#Scale factor for buff icons.
		#Range: 0.1 ~ 5.0
		buffFrameScaleFactor = 0.5
		#Vertical offset of buff bar from the bottom center HUD.
		#Range: -100 ~ 100
		buffBarVerticalOffset = 2
		#Horizontal gap between buff icons.
		#Range: 0 ~ 50
		buffIconHorizontalGap = 2
		#Vertical gap between rows of buff icons.
		#Range: 0 ~ 50
		buffRowVerticalGap = 2

