#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Mar 05 05:11:00 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Derivative Main d24.4.14.zip
enableShaders=false
